### PR TITLE
Raspberry PI Pico hardware bench

### PR DESCRIPTION
**Pull request by rfuest**
Here is a first version of a Raspberry PI Pico based breakout board for the display modules. It is pretty bare bones and does only contain a rotary encoder in addition to the display modules. But I've added an additional connector for a SSD1306 based 0.91" display, which did fit in the gap between the other OLEDs and it should be possible to configure the addresses to not conflict which each other.

The PCB is 120mm x 130mm.

PCB without modules:
hardware-bench

And with modules:
hardware-bench-with-display

### CODE REVIEW

**Comment by rfuest** [comment]
@jamwaffles I don't seem to have the necessary permissions to request a review in this repo, but I would appreciate some feedback.

**Review by jamwaffles — COMMENTED** [review]
I added the e-g core team as admins, so hopefully now you should be able to request reviews and other things :)

Nice work! Going off the screenshots alone, it looks good so far aside from two things that stand out to me:

1. Could we add the display controller ICs to the silkscreen labels? It makes it a bit more obvious which module should go where. That said, some modules are interchangeable (e.g. SH1106 and SSD1306) so maybe we should leave them agnostic.
2. How is the rPi debug port accessed?

**Comment by rfuest** [comment]
> I added the e-g core team as admins, so hopefully now you should be able to request reviews and other things :)

Thanks.

> 1\. Could we add the display controller ICs to the silkscreen labels? It makes it a bit more obvious which module should go where. That said, some modules are interchangeable (e.g. SH1106 and SSD1306) so maybe we should leave them agnostic.

I had considered to add the controllers to the silkscreen, but ultimately decided against it because of the interchangeability you mentioned. Do you think it would be enough to mention the default configuration somewhere else, like the docs for a BSP crate for the PCB?

> 2\. How is the rPi debug port accessed?

The SWD connector is located under the lower left display, above the Rust logo. You should be able to read the labels if you view the first image in the original size.

**Comment by rfuest** [comment]
Or we could add a table of the default display modules on the back side of the PCB:
grafik

**Comment by jamwaffles** [comment]
> Do you think it would be enough to mention the default configuration somewhere else, like the docs for a BSP crate for the PCB?

Works for me. If we also want it on the PCB, perhaps the wording should be something like "Suggested display modules" or similar.

> The SWD connector is located under the lower left display, above the Rust logo. You should be able to read the labels if you view the first image in the original size.

Thanks for pointing it out. I was looking around the pico, expecting the port to be in the top right region of the board :)

**Comment by rfuest** [comment]
I've added a bit more information to the table and changed the title:
grafik

> Thanks for pointing it out. I was looking around the pico, expecting the port to be in the top right region of the board :)

Moving the SWD connector to the left edge of the PCB did make the layout easier, otherwise I might have put it in the top right region.

**Comment by jamwaffles** [comment]
Looks good to me

**Comment by rfuest** [comment]
> Looks good to me

Did that comment refer to the whole PCB or the changes to the silkscreen? I would like to order the PCBs soon, but I would also prefer if someone else has at least checked that I didn't make any obvious stupid mistakes in the schematic or PCB.

**Comment by jamwaffles** [comment]
Ah, just the silkscreen. I'll take a look at the PCB when I have a moment - hopefully tomorrow evening or Monday.

**Comment by rfuest** [comment]
I've updated the PCB a bit to use normal 2.54mm pitch jumpers instead of solder jumpers to make it easier to test I2C modules with different pinouts. It's now also possible to select between 3V3 and 5V supply voltage for the OLED modules. I had some issues with one module when it was supplied with 3V3.

**Review by jamwaffles — APPROVED** [review]
I gave the schematic and PCB a look over and nothing stood out to me. This is my first hardware review but hopefully I didn't miss anything. I didn't check the connections to the Pico so I hope you hooked the right pins up to the right PIO modules.

This PR is huge, but could be shrunk down a bit - there are a few files like images and READMEs from the imported libraries which could either bit gitignored or deleted.

**Pull request merged**
